# Site settings
title: Freiwillige Feuerwehr St. Gertraudi
description: >
  Willkommen auf der offiziellen Website der Freiwilligen Feuerwehr St. Gertraudi!
baseurl: ''
url: https://ffgai.info

# Build settings
markdown: kramdown
sass:
  style: :compressed

# Exclusions
exclude: [
  '.gitignore',
  'ReadMe.md',
  'CNAME',
  'Gemfile',
  'Gemfile.lock',
  'node_modules',
  'package.json'
]

# Collections
collections:
  events:
    output: true
    permalink: /events/:path.html
